apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: intro-web
  namespace: dashaun-io
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/max-scale: "100"
        autoscaling.knative.dev/metric: "rps"
        autoscaling.knative.dev/target: "1"
    spec:
      containers:
        - image: dashaun/io.dashaun.web.intro:v0.0.5