apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: gateway-service
  namespace: dashaun-io
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/activation-scale: "3"
        autoscaling.knative.dev/max-scale: "3"
        autoscaling.knative.dev/metric: "rps"
        autoscaling.knative.dev/target: "1"
        autoscaling.knative.dev/window: "15s"
    spec:
      containers:
        - image: dashaun/io.dashaun.service.gateway:v0.0.3
          env:
          - name: ZIPKIN_ENDPOINT
            value: http://openzipkin.dashaun-io.svc.cluster.local:9411/api/v2/spans
