apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: hello-service
  namespace: dashaun-io
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/max-scale: "3"
        autoscaling.knative.dev/window: "300s"
    spec:
      containers:
        - image: dashaun/io.dashaun.service.hello:v0.0.1
          env:
          - name: ZIPKIN_ENDPOINT
            value: http://openzipkin.dashaun-io.svc.cluster.local:9411/api/v2/spans